version: '2'
services:
  logger:
    build: ./deploy/log/
    restart: always
    volumes:
      - /var/log/i.yiizh.com/:/var/log/docker/
    ports:
      - 10200:514
  frontend:
    build: .
    ports:
      - "127.0.0.1:10201:80"
    depends_on:
      - logger
    logging:
      driver: "syslog"
      options:
        syslog-address: "tcp://127.0.0.1:10200"
        tag: "frontend"
    restart: always
    volumes:
      - /opt/composer/cache:/opt/composer/cache
    env_file: .env
    dns:
      - 223.5.5.5
      - 223.6.6.6
      - 8.8.8.8
      - 8.4.4.4